sudo: false

language: generic

os:
  - linux
  - osx

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

# Required for stack
addons:
  apt:
    packages:
      - libgmp-dev
    
before_install:
  - mkdir -p ~/.local/bin
  - export PATH="$HOME/.local/bin:$PATH"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      travis_retry curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi

install:
  - stack --no-terminal --install-ghc test --only-dependencies
  
script:
  - stack --no-terminal test

before_deploy:
  - find .stack-work/install -type f -path '*/bin/elocrypt' | while read line; do tar cvzf elocrypt-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-bin.tar.gz -C $(dirname $line) $(basename $line); done

deploy:
  # Not sure what I'm doing here...
  # before_deploy:
  # - find .stack-work/install -type f -path '*/bin/elocrypt' | while read line; do tar cvzf elocrypt-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-bin.tar.gz -C $(dirname $line) $(basename $line); done
  provider: releases
  api_key:
    secure: aNb9BT0FCT2qpspL0I+rxZDpdSQXy4yQ5+7Kkw9bI9+RSA4XSSVfE7pRIaGuSWVPN82oksKYooaRIxVeWoo9BMizyhROhtNr9EfcCjtFH4DXkT8SVtm/Cqk/X5mGjoL8uV1vKs1E+Wx0XVrZ8nwDAEcaBsM+3h3bDK9fnanr32Y=
  file: elocrypt-*-bin.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: sgillespie/elocrypt
    tags: true
  draft: true
  overwrite: true
